version: "0.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
      python manage.py collectstatic --noinput 
      &&
      python manage.py migrate 
      &&
      python manage.py import_excel Project-Management-Sample-Data.xlsx 
      &&
      python manage.py runserver 0.0.0.0:8080
      "
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - "5432:5432"
volumes:
  postgres_data: